# FriendlyELEC NanoPi R5C (RK3568B2, 2x RTL8125B 2.5GbE)
# https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R5C
# Conf to create sdcard/eMMC bootable image for R5C. Needs the u-boot files!

export PRODUCT_KERNEL=SMP-ARM
export PRODUCT_TARGET=arm64
export PRODUCT_ARCH=aarch64
export PRODUCT_WANTS="u-boot-nanopi-r5c"
export PRODUCT_WANTS_CROSS="aarch64-binutils qemu-user-static"
export PRODUCT_ADDITIONS="realtek-re-kmod198"
export PRODUCT_COMSPEED=1500000

# Adjust the start of EFI partition to let space for R5C boot code
export ARM_FAT_SIZE="32m -b 64m"

export ARM_UBOOT_DIR="/usr/local/share/u-boot/u-boot-nanopi-r5c"

arm_install_uboot()
{
        sysctl kern.geom.debugflags=0x10
        dd if=${ARM_UBOOT_DIR}/idbloader.img of=/dev/${DEV} seek=64 bs=512 conv=sync
        dd if=${ARM_UBOOT_DIR}/u-boot.itb of=/dev/${DEV} seek=16384 bs=512 conv=sync
        sysctl kern.geom.debugflags=0x0
}
