# FriendlyELEC NanoPi R5C (RK3568B2, 2x RTL8125B 2.5GbE)
# Conf to create a bootable USB image for R5C. The board still boots
# u-boot from sdcard/eMMC, which then chainloads the loader from USB.

export PRODUCT_KERNEL=SMP-ARM
export PRODUCT_TARGET=arm64
export PRODUCT_ARCH=aarch64
export PRODUCT_WANTS_CROSS="aarch64-binutils qemu-user-static"
export PRODUCT_ADDITIONS="realtek-re-kmod198"
export PRODUCT_COMSPEED=1500000

arm_install_uboot()
{
}
